### ISSUE TITLE
Overhaul Person + Person builder methods

### ISSUE THREAD

**Issue by mynameizzhafeez** [AY2223S2-CS2103T-W14-2/tp#15]
## Todo

- [ ] User is a Singleton class object
- [ ] Person have Telegram Handle and Module Tags
- [ ] Overhaul Person, Person methods
