### ISSUE TITLE
As a user, I can update my profile to customise the application’s functionality

### ISSUE THREAD

**Issue by mynameizzhafeez** [AY2223S2-CS2103T-W14-2/tp#25]
## To Do
- [X] Implement User Profile
- [X] Implement User Commands
- [X] Modify Edit Command to edit User
- [ ] Modify Tag Command to edit User
- [ ] Modify Untag Command to edit User
